### model
model_name_or_path: "/home/Data1/ziyue/ckpt/ZhipuAI/glm-4-9b-chat"
trust_remote_code: true  # 必须在此处也声明
quantization_bit: 8
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: huatuo
template: glm4
cutoff_len: 512
max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 1

### output
output_dir: "/home/Data1/ziyue/ckpt"
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500